spring.application.name=Fibonacci
spring.datasource.url=jdbc:mysql://localhost:3306/fibodb
spring.datasource.username=root
spring.datasource.password=Mapple28!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
